[package]
name = "si_py_sens_be"
version = "0.1.0"
authors = ["Wolfgang Ginolas <wolfgang.ginolas@gwif.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"